# Generated by Django 3.2.7 on 2021-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timestamp',
        ),
    ]
